#!/bin/bash
# Generated by build.py — copies Teacher's Eye launchers to the Desktop.
DESKTOP="$HOME/Desktop"
mkdir -p "$DESKTOP"
cp -f "/mnt/c/Users/Аслан/TeachEye/dist/TeacherEye_Student/TeacherEye_Student.desktop" "$DESKTOP/"
chmod +x "$DESKTOP/TeacherEye_Student.desktop"
cp -f "/mnt/c/Users/Аслан/TeachEye/dist/TeacherEye_Teacher/TeacherEye_Teacher.desktop" "$DESKTOP/"
chmod +x "$DESKTOP/TeacherEye_Teacher.desktop"
cp -f "/mnt/c/Users/Аслан/TeachEye/dist/TeacherEye_Admin/TeacherEye_Admin.desktop" "$DESKTOP/"
chmod +x "$DESKTOP/TeacherEye_Admin.desktop"
echo "Ярлыки скопированы на рабочий стол. Двойной клик → запуск."
