# [VIBE-CONTEXT]
# Role: AI feedback and task-analysis engine for Teacher's Eye — wraps Gemini 1.5 Flash.
# State: Session 4 — added analyze_task() for multimodal task pre-analysis; student feedback
#        now receives the pre-computed task analysis as context for sharper hints.
# Why: Isolating all LLM logic here keeps server/main.py clean and makes it trivial to
#      swap models or add prompt versioning without touching routing code.

import io

import google.generativeai as genai
from PIL import Image

from shared.config import GEMINI_API_KEY

# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

_FEEDBACK_SYSTEM_PROMPT = """Ты — добрый и терпеливый ассистент учителя информатики в школе. \
Твоя задача — помочь ученику 8–9 класса самостоятельно найти ошибку в своём коде или решении.

Правила, которые ты должен соблюдать неукоснительно:
1. Никогда не пиши исправленный код и не давай готовый ответ.
2. Объясняй ошибку простыми словами, понятными 14-летнему ребёнку.
3. Дай подсказку: в какую сторону думать, что проверить, на что обратить внимание.
4. Будь подбадривающим — напомни, что ошибаться нормально и это часть обучения.
5. Если код выглядит правильным — похвали ученика и предложи подумать над краевыми случаями.
6. Отвечай на русском языке. Максимальная длина ответа — 5–7 предложений."""

_ANALYSIS_PROMPT_TEMPLATE = """Ты — опытный учитель информатики. Тебе дано изображение задачи \
и правильное решение от учителя.

Выполни следующее:
1. Кратко опиши, в чём суть задачи (1–2 предложения).
2. Разбери правильное решение: что в нём ключевое, какой алгоритм или концепция используется.
3. Перечисли 3–5 типичных ошибок, которые может допустить ученик 8–9 класса при решении этой задачи.

Правильное решение учителя:
{solution_code}

Отвечай на русском языке. Будь конкретным и кратким."""

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _configure() -> None:
    """Configures the Gemini client; raises ValueError if the key is missing."""
    if GEMINI_API_KEY == "YOUR_GEMINI_API_KEY_HERE" or not GEMINI_API_KEY:
        raise ValueError(
            "GEMINI_API_KEY is not set. "
            "Replace the placeholder in shared/config.py before using the AI engine."
        )
    genai.configure(api_key=GEMINI_API_KEY)


def _image_from_bytes(image_bytes: bytes) -> Image.Image:
    """Converts raw bytes to a PIL Image for Gemini multimodal input."""
    return Image.open(io.BytesIO(image_bytes))


# ---------------------------------------------------------------------------
# Public API — task analysis
# ---------------------------------------------------------------------------

def analyze_task(image_bytes: bytes, solution_code: str) -> str:
    """Sends the task screenshot + teacher's solution to Gemini for pre-analysis.

    Returns a structured string describing the task, the correct approach, and
    typical student mistakes. This is stored in tasks.ai_analysis and later
    injected as context into every student-feedback prompt for this task.

    Raises ValueError if the API key is not configured.
    Raises RuntimeError on any Gemini API or network failure.
    """
    _configure()
    # [AI-INTERACTION] Multimodal call: image (task screenshot) + text (solution + prompt).
    model = genai.GenerativeModel(model_name="gemini-1.5-flash")
    prompt = _ANALYSIS_PROMPT_TEMPLATE.format(solution_code=solution_code or "(решение не указано)")
    image = _image_from_bytes(image_bytes)
    try:
        response = model.generate_content([image, prompt])
        return response.text.strip()
    except Exception as exc:
        raise RuntimeError(f"Gemini analyze_task call failed: {exc}") from exc


def analyze_task_or_fallback(image_bytes: bytes, solution_code: str) -> str:
    """Convenience wrapper for analyze_task that never raises — returns a stub on failure."""
    # [VIBE-CHECK] Monitor fallback frequency — high rate signals missing key or quota exhaustion.
    try:
        return analyze_task(image_bytes, solution_code)
    except ValueError:
        return "(анализ недоступен: ключ Gemini не настроен)"
    except RuntimeError:
        return "(анализ недоступен: ошибка сети или сервиса Gemini)"


# ---------------------------------------------------------------------------
# Public API — student feedback
# ---------------------------------------------------------------------------

def get_student_feedback(
    solution_text: str,
    task_type: str = "",
    task_analysis: str = "",
) -> str:
    """Sends the student's solution to Gemini and returns a supportive teacher hint.

    task_analysis (pre-generated by analyze_task) is injected as context so Gemini
    already knows the task description, correct approach, and typical mistakes —
    this makes the hint significantly more targeted than a generic prompt.

    Deliberately never includes the correct answer — the system prompt enforces
    a Socratic, hint-only style so the student must still do the cognitive work.

    Raises ValueError if the API key has not been configured.
    Raises RuntimeError on any Gemini API or network failure.
    """
    _configure()
    # [AI-INTERACTION] Single-turn generation with optional pre-analysis context.
    model = genai.GenerativeModel(
        model_name="gemini-1.5-flash",
        system_instruction=_FEEDBACK_SYSTEM_PROMPT,
    )

    task_context = f"Тип задания: {task_type}\n\n" if task_type else ""
    analysis_context = (
        f"Предварительный анализ задачи (описание, правильный подход, типичные ошибки):\n"
        f"{task_analysis}\n\n"
        if task_analysis else ""
    )
    prompt = (
        f"{task_context}"
        f"{analysis_context}"
        f"Ответ/код ученика:\n{solution_text}"
    )

    try:
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as exc:
        raise RuntimeError(f"Gemini API call failed: {exc}") from exc


def get_feedback_or_fallback(
    solution_text: str,
    task_type: str = "",
    task_analysis: str = "",
) -> str:
    """Convenience wrapper that always returns a string — never raises.

    Returns the AI feedback on success, or a user-facing fallback message on any
    failure (missing key, network error, quota exceeded, etc.) so callers never
    have to guard against exceptions.
    """
    # [VIBE-CHECK] Monitor fallback frequency in production — high rate means key is missing or quota hit.
    try:
        return get_student_feedback(solution_text, task_type, task_analysis)
    except ValueError:
        return (
            "⚠️ ИИ-подсказки временно недоступны: ключ Gemini не настроен. "
            "Спроси учителя напрямую!"
        )
    except RuntimeError:
        return (
            "⚠️ Не удалось получить подсказку от учителя — проблема с сетью или сервисом. "
            "Попробуй отправить решение ещё раз позже."
        )
