# [VIBE-CONTEXT]
# Role: Defines all SQLAlchemy ORM models and the database engine for the Teacher's Eye backend.
# State: Session 11 — classic session/submission models remain intact, and Lesson Mode adds
#        lessons, scenes, widgets, lesson runs, participant state, and code-run history.
# Why: SQLite keeps the server fully self-contained during development; JSON-backed text fields
#      let Lesson Mode evolve quickly before a heavier schema or external DB is needed.

from datetime import datetime

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    LargeBinary,
    String,
    Text,
    UniqueConstraint,
    create_engine,
)
from sqlalchemy.orm import declarative_base, relationship, sessionmaker

DATABASE_URL = "sqlite:///./teacher_eye.db"

# connect_args is required for SQLite to work safely with FastAPI's thread-per-request model.
engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(bind=engine, autocommit=False, autoflush=False)

Base = declarative_base()


class Student(Base):
    """Represents a registered student in the system.

    Identity is (name, class_name) so two students with identical ФИО in different
    classes are stored as separate records. Pre-Session-9 records have class_name=""
    and are treated as a legacy "no class" bucket.
    last_seen is updated by the client heartbeat (POST /ping) every 30 seconds
    and used by the admin dashboard to show online/offline status.
    """

    __tablename__ = "students"
    __table_args__ = (
        # [LOGIC-ANCHOR] Composite unique: same name is allowed across classes but not within one.
        UniqueConstraint("name", "class_name", name="uq_student_name_class"),
    )

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    class_name = Column(String, nullable=False, default="")
    created_at = Column(DateTime, default=datetime.utcnow)
    # [LOGIC-ANCHOR] last_seen drives the online indicator in the admin dashboard.
    # NULL means the student has never sent a heartbeat (pre-Session 5 records).
    last_seen = Column(DateTime, nullable=True)

    sessions = relationship("Session", back_populates="student")


class Task(Base):
    """A content unit (EGE exam task) uploaded by the teacher as a screenshot + solution.

    image_data holds the raw PNG bytes pasted by the teacher via Ctrl+V.
    solution_code is the teacher's correct solution used to pre-analyse the task.
    ai_analysis is generated by Gemini in the background after upload and injected
    as context into every student-feedback prompt for this task.
    """

    __tablename__ = "tasks"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=False)
    task_type = Column(String)
    # [LOGIC-ANCHOR] image_data stores raw PNG bytes — never returned in list endpoints, only via /tasks/{id}/image.
    image_data = Column(LargeBinary, nullable=True)
    solution_code = Column(Text, nullable=True)
    # Starts as NULL; populated asynchronously by Gemini after the teacher uploads the task.
    ai_analysis = Column(Text, nullable=True)

    submissions = relationship("Submission", back_populates="task")


class Session(Base):
    """A single focus window for one student.

    status transitions: "active" → "ended" (timer) or "terminated" (teacher).
    end_time is null while the session is running.
    session_code is the МЭШ-style number shown to the student at login.
    duration_seconds is the length of the session — set by the teacher before students log in
    via the Teacher Panel; defaults to SESSION_DURATION_SECONDS if not configured.
    Pre-Session-10 records have duration_seconds=NULL and fall back to the 50-min constant.
    """

    __tablename__ = "sessions"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    start_time = Column(DateTime, default=datetime.utcnow)
    end_time = Column(DateTime, nullable=True)
    # [LOGIC-ANCHOR] status is the canonical truth about whether the focus window is open.
    status = Column(String, default="active")
    # [LOGIC-ANCHOR] session_code is assigned at login and never changes for the lifetime of the session.
    session_code = Column(Integer, nullable=True)
    # [LOGIC-ANCHOR] duration_seconds is baked into the session at login time so changing the
    # config mid-lesson doesn't retroactively alter sessions already in progress.
    duration_seconds = Column(Integer, nullable=True)

    student = relationship("Student", back_populates="sessions")
    submissions = relationship("Submission", back_populates="session")
    lesson_participant_states = relationship("LessonParticipantState", back_populates="session")


class Submission(Base):
    """A single piece of student work submitted during a session.

    task_id is nullable so free-form submissions can still be stored if the
    client had a task-fetch failure. ai_feedback is populated asynchronously
    by the AI engine after the submission is persisted.
    """

    __tablename__ = "submissions"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("sessions.id"), nullable=False)
    task_id = Column(Integer, ForeignKey("tasks.id"), nullable=True)
    solution_text = Column(Text)
    submitted_at = Column(DateTime, default=datetime.utcnow)
    # [LOGIC-ANCHOR] Starts as NULL; the background Gemini task writes here once feedback is ready.
    ai_feedback = Column(Text, nullable=True)

    session = relationship("Session", back_populates="submissions")
    task = relationship("Task", back_populates="submissions")


class Lesson(Base):
    """Reusable lesson content for Lesson Mode.

    A lesson belongs to the shared school library and is composed of ordered scenes.
    Tags, scene layouts, and widget configs are stored as JSON text for flexibility while
    the product is still discovering its ideal authoring model.
    """

    __tablename__ = "lessons"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=False)
    grade_band = Column(String, nullable=True)
    topic = Column(String, nullable=True)
    level = Column(String, nullable=True)
    author_name = Column(String, nullable=True)
    summary = Column(Text, nullable=True)
    tags_json = Column(Text, nullable=True)
    status = Column(String, default="draft")
    is_template = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    scenes = relationship("LessonScene", back_populates="lesson", cascade="all, delete-orphan")
    runs = relationship("LessonRun", back_populates="lesson")


class LessonScene(Base):
    """One screen in a lesson flow.

    Scenes are ordered within a lesson and hold widget instances plus lightweight layout metadata.
    The teacher unlocks them progressively while students can keep local state per scene.
    """

    __tablename__ = "lesson_scenes"

    id = Column(Integer, primary_key=True, index=True)
    lesson_id = Column(Integer, ForeignKey("lessons.id"), nullable=False)
    title = Column(String, nullable=False)
    scene_type = Column(String, default="board")
    order_index = Column(Integer, default=0)
    layout_json = Column(Text, nullable=True)
    notes_text = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    lesson = relationship("Lesson", back_populates="scenes")
    widgets = relationship("LessonWidget", back_populates="scene", cascade="all, delete-orphan")


class LessonWidget(Base):
    """A reusable interactive block placed on a lesson scene.

    widget_type selects the mechanic (powers_of_two_picker, multiple_choice, etc.).
    config_json stores the educational logic while layout_json stores placement on the board.
    """

    __tablename__ = "lesson_widgets"

    id = Column(Integer, primary_key=True, index=True)
    scene_id = Column(Integer, ForeignKey("lesson_scenes.id"), nullable=False)
    widget_type = Column(String, nullable=False)
    title = Column(String, nullable=True)
    order_index = Column(Integer, default=0)
    layout_json = Column(Text, nullable=True)
    config_json = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    scene = relationship("LessonScene", back_populates="widgets")


class LessonRun(Base):
    """A live classroom instance of a lesson.

    The lesson is static library content; LessonRun is the teacher-driven runtime:
    current scene, unlocked frontier, and any board-level state shared with the class.
    """

    __tablename__ = "lesson_runs"
    __table_args__ = (
        Index("ix_lesson_runs_lesson_status", "lesson_id", "status"),
    )

    id = Column(Integer, primary_key=True, index=True)
    lesson_id = Column(Integer, ForeignKey("lessons.id"), nullable=False)
    class_name = Column(String, nullable=True)
    status = Column(String, default="active")
    current_scene_index = Column(Integer, default=0)
    highest_unlocked_scene_index = Column(Integer, default=0)
    teacher_state_json = Column(Text, nullable=True)
    lesson_snapshot_json = Column(Text, nullable=True)
    started_at = Column(DateTime, default=datetime.utcnow)
    ended_at = Column(DateTime, nullable=True)

    lesson = relationship("Lesson", back_populates="runs")
    participants = relationship("LessonParticipantState", back_populates="lesson_run", cascade="all, delete-orphan")


class LessonParticipantState(Base):
    """Per-student runtime state inside a live lesson run.

    Stores the student's current scene, stars, activity, preview payload, and widget progress.
    This is the backbone for the mini-preview wall and the post-lesson analytics summary.
    """

    __tablename__ = "lesson_participant_states"
    __table_args__ = (
        UniqueConstraint("lesson_run_id", "session_id", name="uq_lesson_run_session"),
        Index("ix_lesson_participant_states_run", "lesson_run_id"),
        Index("ix_lesson_participant_states_session", "session_id"),
    )

    id = Column(Integer, primary_key=True, index=True)
    lesson_run_id = Column(Integer, ForeignKey("lesson_runs.id"), nullable=False)
    session_id = Column(Integer, ForeignKey("sessions.id"), nullable=False)
    current_scene_index = Column(Integer, default=0)
    highest_unlocked_scene_index = Column(Integer, default=0)
    stars_tenths = Column(Integer, default=0)
    activity_points = Column(Integer, default=0)
    preview_json = Column(Text, nullable=True)
    progress_json = Column(Text, nullable=True)
    progress_version = Column(Integer, default=0)
    last_event_at = Column(DateTime, default=datetime.utcnow)
    last_preview_at = Column(DateTime, nullable=True)

    lesson_run = relationship("LessonRun", back_populates="participants")
    session = relationship("Session", back_populates="lesson_participant_states")
    code_runs = relationship("CodeRun", back_populates="participant_state", cascade="all, delete-orphan")
    star_events = relationship("LessonStarEvent", back_populates="participant_state", cascade="all, delete-orphan")


class CodeRun(Base):
    """Stores one embedded Python execution attempt for Lesson Mode.

    Code runs are tied to a participant state so the teacher can later inspect what was executed,
    what output was produced, and what interpreter errors the student hit.
    """

    __tablename__ = "code_runs"
    __table_args__ = (
        Index("ix_code_runs_participant_created", "participant_state_id", "created_at"),
    )

    id = Column(Integer, primary_key=True, index=True)
    participant_state_id = Column(Integer, ForeignKey("lesson_participant_states.id"), nullable=False)
    scene_id = Column(Integer, ForeignKey("lesson_scenes.id"), nullable=True)
    source_code = Column(Text, nullable=False)
    status = Column(String, default="ok")
    exit_code = Column(Integer, nullable=True)
    stdout_text = Column(Text, nullable=True)
    stderr_text = Column(Text, nullable=True)
    friendly_error = Column(Text, nullable=True)
    duration_ms = Column(Integer, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    participant_state = relationship("LessonParticipantState", back_populates="code_runs")
    scene = relationship("LessonScene")


class LessonStarEvent(Base):
    """Append-only log of star changes for classroom audit and recap views.

    Star totals still live on LessonParticipantState for fast reads, while this table keeps the
    reason/source trail for manual rewards and automatic widget-completion bonuses.
    """

    __tablename__ = "lesson_star_events"
    __table_args__ = (
        Index("ix_lesson_star_events_participant_created", "participant_state_id", "created_at"),
    )

    id = Column(Integer, primary_key=True, index=True)
    participant_state_id = Column(Integer, ForeignKey("lesson_participant_states.id"), nullable=False)
    delta_tenths = Column(Integer, nullable=False, default=0)
    reason = Column(Text, nullable=True)
    source = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    participant_state = relationship("LessonParticipantState", back_populates="star_events")
